
server:
  port: 8080


sip:
  # [必须修改] 本机的IP, 必须是网卡上的IP，用于sip下协议栈监听ip，如果监听所有设置为0.0.0.0
  monitor-ip: 0.0.0.0
  # [必须修改] 本机的IP
  ip: 192.168.31.
  # [可选] 没有任何业务需求，仅仅是在前端展示的时候用
  show-ip:
  # 国标注册外网IP
  sip-ip: 192.168.31.6
  # [可选] 28181服务监听的端口
  port: 5080
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 3402000000
  # [可选]
  id: 34020000002000000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  # password: Vedio@test
  password: 12345678
  # [可选] 心跳超时时间， 超时时间为该设置的三倍
  keepalive-timeout: 100
  # [可选] 国标级联注册失败，再次发起注册的时间间隔。 默认60秒
  register-time-interval: 60
  # [可选] 云台控制速度
  ptz-speed: 50
  # TODO [可选] 收到心跳后自动上线， 重启服务后会将所有设备置为离线，默认false，等待注册后上线。设置为true则收到心跳设置为上线。
  keepalliveToOnline: true
  # 是否存储alarm信息
  alarm: false
spring:
  main:
    allow-circular-references: true
